#!/bin/sh
[ "$1" = "" ] && echo "please provide valid path to kmc job" && exit

[ ! -e "$1" ] && echo "$1 does not exist" && exit

cp $1/input.* .
cp $1/scaling.data .
cp $1/submit_training_debug.sh .

