#!/bin/sh
squeue -u "$USER" --format "%A %t %C %M %Z %N" | awk '{printf "%8s %3s %4s %10s %10s (%-s)\n",$1,$2,$3,$4,$5,$6}' | sed 's|()||'


#echo
#sacct -u $USER --starttime 2018-12-01 --format=JobID,state,WorkDir,Comment #| grep -v "[0-9].bat" | grep -v "[0-9].ext" | grep -v "[0-9]\.0"

