# .bash_profile

# Get the aliases and functions
#if [ -f ~/.bashrc ]; then
#	. ~/.bashrc
#fi

# User specific environment and startup programs
#echo PATH-
#echo PATH- $PATH
#echo PATH-
#PATH=$PATH:$HOME/.local/bin:$HOME/bin
#export PATH

#echo "in .bash_profile, `hostname | grep -o fidis`"

echo '... .bash_profile start'
case "$-" in
  # only for interactive shell login on fidis or daint or cosmopc --> load zsh
  # for interactive shell login on fidis or daint --> load zsh
  # when login to f210 (worknode fidis cluster) or actually any host besides daint / fidis -> do not load zsh
  *i*)
  # THIS LOOP IS ONLY ENTERED FOR INTERACTIVE LOGINS AND NOT OTHERWISE (ssh -C "command")
  # echo hostname `hostname`
  alias e='exit'
  host=`hostname`
  #echo "host:$host:"

  export generalrc="$HOME/Dropbox/Albert/scripts/dotfiles/generalrc"
  source $generalrc/generalrc_necessary_bash.sh  # loads setenv for bash/zsh (not any more)
  myhost=`myhost_get`
  export myhost=$myhost
  #echo "myhost .bash_profile:$myhost:"
  #echo 1
  #echo 1 ZSH:$ZSH_VERSION:
  #echo 1 myh:$myhost:
  #[ "`echo $host | grep -o "^daint"`" = "daint" ] && unset FPATH && exec /bin/zsh -l
  [ "$myhost" = "daint" ] && unset FPATH && exec /bin/zsh -l
  #echo 2
  #echo 2 ZSH:$ZSH_VERSION:
  #[ "`echo $host | grep -o "^fidis"`" = "fidis" ] && /bin/zsh -l #exec /bin/bash
#[ "$myhost" = "fidis" ] && /bin/zsh -l #exec /bin/bash
  [ "$myhost" = "fidis" ] && exec /bin/zsh -l #exec /bin/bash
  #[ "`echo $host`" = "helvetios" ] && /bin/zsh -l #exec /bin/bash
#[ "$myhost" = "helvetios" ] && /bin/zsh -l #exec /bin/bash
  [ "$myhost" = "helvetios" ] && exec /bin/zsh -l #exec /bin/bash
  #[ "`echo $host | grep -o cosmopc15`" = "cosmopc15" ] && /bin/zsh -l #exec /bin/bash
#[ "$myhost" = "cosmopc15" ] && /bin/zsh -l #exec /bin/bash
  [ "$myhost" = "cosmopc15" ] && exec /bin/zsh -l #exec /bin/bash
   ;;
esac

## >>> conda initialize >>>
## !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/Users/glensk/anaconda2/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/Users/glensk/anaconda2/etc/profile.d/conda.sh" ]; then
#        . "/Users/glensk/anaconda2/etc/profile.d/conda.sh"
#    else
#        export PATH="/Users/glensk/anaconda2/bin:$PATH"
#    fi
#fi
#unset __conda_setup
## <<< conda initialize <<<

